In [1]:
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.lines as lines
import scipy
import math

In [2]:
# MOTOR SPECS
Kv = 330
Kt = 60 / ( 2 * math.pi * Kv)
R_phi = 1 ## QUESTION: UNSURE HOW TO CALCULATE ## phase to phase resistance


# PROFILES
angular_position = np.array([1, 2, 3]) # radians
angular_velocity = np.gradient(angular_position) # radians / s

print(angular_position)
print(angular_velocity)

[1 2 3]
[1. 1. 1.]


In [3]:
Kt_phi_bar = Kt ## QUESTION: IS THIS THE SAME ##
I_phi_bar = 1  ## QUESTION: HOW TO GET ## Amplitude of the phase current

torque = (3 / 2) * Kt_phi_bar * I_phi_bar

Kt_phi_a = -Kt * np.sin(angular_position)
Kt_phi_b = -Kt * np.sin(angular_position - (2 * math.pi / 3))
Kt_phi_c = -Kt * np.sin(angular_position + (2 * math.pi / 3))
backEMF = Kt_phi_a * angular_velocity + Kt_phi_b * angular_velocity + Kt_phi_c * angular_velocity

R_ll = 2 * R_phi

R_phi = (1/2) * R_ll
I_q = math.sqrt(3/2) * I_phi_bar
power_loss = I_q * I_q * R_phi

print(torque)
print(backEMF)

[-7.45931095e-17 -8.32667268e-17 -2.77555756e-17]
[-7.45931095e-17 -8.32667268e-17 -2.77555756e-17]


Luke being a dumb dumb

Ia = -I_phi_bar * np.sin(angular_position)
Ib = -I_phi_bar * np.sin(angular_position - (2 * math.pi / 3))
Ic = -I_phi_bar * np.sin(angular_position + (2 * math.pi / 3))

torque_phi_A = Ia * Kt_phi_a
torque_phi_B = Ib * Kt_phi_b
torque_phi_C = Ic * Kt_phi_c